repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.12
  hooks:
    - id: ruff-check
      args: [ --fix, --select, I ]
    - id: ruff-format

- repo: local
  hooks:
    - id: taplo-format
      name: toml format
      entry: uvx taplo format
      language: system
      files: \.toml$